# Default values for roxsross-stats-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

roxsrossStatsSettings:
  ytAPIKey: ""
  ytChannelID: ""

image:
  repository: roxsross12/go-rest-k8s:1.0.0
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1001

securityContext:
  runAsUser: 1001
  runAsGroup: 1001
  runAsNonRoot: true

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations:
    {}
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 150m
    memory: 128Mi
  requests:
    cpu: 100m

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
