name: ci

on:
  push:
    tags:
      - "*"
    branches:
      - "master"

jobs:
  helmRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: custom packaging
        run: |
          VERSION="0.1.0"
          echo $VERSION
          rm -rf .cr-release-packages
          mkdir -p .cr-release-packages
          ls -la
          helm package charts/roxsross-stats-chart --app-version=${VERSION:1} --version=${VERSION:1} --destination=.cr-release-packages

      # - name: Run chart-releaser
      #   # switch back to helm/chart-releaser-action if this contribution is ever merged
      #   uses: askcloudarchitech/chart-releaser-action@skip-packaging-option
      #   with:
      #     skip_packaging: true
      #   env:
      #     CR_TOKEN: "${{ secrets.CR_TOKEN }}"
